Repository NikolaySavenko/bignum-wizard, pull requests merged in 2021-03, with the labels that each got.

#2 Bignum subtraction
  BigNumWizardApp/BigNumWizardShared/BigNum.cs
  BigNumWizardApp/BigNumWizardTests/SubtractionBigNumTest.cs
Labels: enhancement

#3 Negative support
  BigNumWizardApp/BigNumWizardShared/BigNum.cs
  BigNumWizardApp/BigNumWizardTests/AbsTest.cs
  BigNumWizardApp/BigNumWizardTests/BigNumWizardTests.csproj
  BigNumWizardApp/BigNumWizardTests/Compare/AbiggerB/CompareNegativeTests.cs
  BigNumWizardApp/BigNumWizardTests/Compare/AbiggerB/ComparePositiveTests.cs
  BigNumWizardApp/BigNumWizardTests/Negative/SumTest.cs
  BigNumWizardApp/BigNumWizardTests/Positive/SubtractionBigNumTest.cs
  BigNumWizardApp/BigNumWizardTests/Positive/SumBigNumTest.cs
Labels: enhancement

#5 Lukina
  BigNumWizardApp/BigNumWizardShared/N2_6.cs
  BigNumWizardApp/BigNumWizardShared/z2_3.cs
Labels: enhancement

#6 Ivanov
  BigNumWizardApp/BigNumWizardShared/Absolute.cs
  BigNumWizardApp/BigNumWizardShared/Rational.cs
Labels: enhancement

#8 Insert support
  BigNumWizardApp/BigNumWizardApp/ADD_NN_NPage.xaml
  BigNumWizardApp/BigNumWizardApp/ADD_NN_NPage.xaml.cs
  BigNumWizardApp/BigNumWizardApp/App.xaml
  BigNumWizardApp/BigNumWizardApp/BigNumWizardApp.csproj
  BigNumWizardApp/BigNumWizardApp/MainPage.xaml
  BigNumWizardApp/BigNumWizardApp/MainPage.xaml.cs
  BigNumWizardApp/BigNumWizardApp/SUB_NN_N.xaml
  BigNumWizardApp/BigNumWizardApp/SUB_NN_N.xaml.cs
  BigNumWizardApp/BigNumWizardApp/SumNNPage.cs
  BigNumWizardApp/BigNumWizardShared/Absolute.cs
  BigNumWizardApp/BigNumWizardShared/BigNum.cs
  BigNumWizardApp/BigNumWizardShared/BigNumWizardShared.csproj
  BigNumWizardApp/BigNumWizardShared/N2_6.cs
  BigNumWizardApp/BigNumWizardShared/Natural1_5.cs
  BigNumWizardApp/BigNumWizardShared/Rational.cs
  BigNumWizardApp/BigNumWizardShared/z2_3.cs
Labels: enhancement

#10 Marina
  BigNumWizardApp/BigNumWizardShared/BigNum.cs
  BigNumWizardApp/BigNumWizardShared/N3_N7.cs
  BigNumWizardApp/BigNumWizardShared/NaturalMultiply.cs
Labels: enhancement

#7 Created fractional module
  BigNumWizardApp/BigNumWizardShared/Fractional.cs
Labels: documentation, duplicate, enhancement

#11 edited N3,N7
  BigNumWizardApp/BigNumWizardShared/N3_N7.cs
Labels: enhancement

#13 Bratsun
  BigNumWizardApp/BigNumWizardShared/Fractional.cs
  BigNumWizardApp/BigNumWizardShared/Q2_3.cs
Labels: enhancement

#12 Osiptsov
  BigNumWizardApp/BigNumWizardShared/BigNumWizardShared.csproj
  BigNumWizardApp/BigNumWizardShared/N4_13.cs
Labels: enhancement

#15 Bugfix/add zero recursion
  BigNumWizardApp/BigNumWizardShared/BigNum.cs
  BigNumWizardApp/BigNumWizardTests/Positive/SubtractionBigNumTest.cs
Labels: bug

#16 new SUB_NN_N and N2 - NZER_N_B
  BigNumWizardApp/BigNumWizardApp/ADD_NN_N_Page.xaml
  BigNumWizardApp/BigNumWizardApp/ADD_NN_N_Page.xaml.cs
  BigNumWizardApp/BigNumWizardApp/BigNumWizardApp.csproj
  BigNumWizardApp/BigNumWizardApp/MainPage.xaml
  BigNumWizardApp/BigNumWizardApp/MainPage.xaml.cs
  BigNumWizardApp/BigNumWizardApp/N2_NZER_N_B_Page.xaml
  BigNumWizardApp/BigNumWizardApp/N2_NZER_N_B_Page.xaml.cs
  BigNumWizardApp/BigNumWizardApp/N_2_NZER_N_B_Page.xaml
  BigNumWizardApp/BigNumWizardApp/N_2_NZER_N_B_Page.xaml.cs
  BigNumWizardApp/BigNumWizardApp/SUB_NN_N.xaml
  BigNumWizardApp/BigNumWizardApp/SUB_NN_N_Page.xaml
  BigNumWizardApp/BigNumWizardApp/SUB_NN_N_Page.xaml.cs
Labels: enhancement

#17 Feature/multiply
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNum.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumMultiplier.cs
  BigNumWizardApp/BigNumWizardTests/Negative/SimpleMultiply.cs
  BigNumWizardApp/BigNumWizardTests/Positive/SimpleMultiply.cs
  BigNumWizardApp/BigNumWizardTests/Positive/SubtractionBigNumTest.cs
Labels: enhancement

#18 Z-6. ADD_ZZ_Z
  BigNumWizardApp/BigNumWizardShared/Z6.cs
Labels: enhancement

#19 P4 - P5
  BigNumWizardApp/BigNumWizardShared/BigNumWizardShared.csproj
  BigNumWizardApp/BigNumWizardShared/P4_5.cs
  BigNumWizardApp/BigNumWizardShared/Polynomial/Polynomial.cs
Labels: enhancement

#21 edited N7
  BigNumWizardApp/BigNumWizardShared/N3_N7.cs
Labels: enhancement

#22 Add Z8
  BigNumWizardApp/BigNumWizardShared/Z8.cs
Labels: enhancement

#25 added P12
  BigNumWizardApp/BigNumWizardShared/P12.cs
Labels: enhancement

#34 fix-mainpage.xaml
  BigNumWizardApp/BigNumWizardApp/MainPage.xaml
  BigNumWizardApp/BigNumWizardApp/SUB_NN_N_Page.xaml.cs
Labels: enhancement

#33 big fractions added
  BigNumWizardApp/BigNumWizardShared/BigFraction/BigFraction.cs
  BigNumWizardApp/BigNumWizardShared/BigNumWizardShared.csproj
Labels: enhancement

#31 Add test for N6
  BigNumWizardApp/BigNumWizardShared/N3_N7.cs
  BigNumWizardApp/BigNumWizardTests/Test_N6.cs
Labels: enhancement

#36 Q8 - div.fractions
  BigNumWizardApp/BigNumWizardShared/N3_N7.cs
  BigNumWizardApp/BigNumWizardShared/Q8.cs
Labels: enhancement

#38 Test for N3
  BigNumWizardApp/BigNumWizardTests/Test_N3.cs
Labels: enhancement

#37 added Q5, Q7 and a little fix to Fractions
  BigNumWizardApp/BigNumWizardShared/BigFraction/BigFraction.cs
  BigNumWizardApp/BigNumWizardShared/BigNumWizardShared.csproj
  BigNumWizardApp/BigNumWizardShared/Q5_7.cs
Labels: enhancement

#39 Feature/divide
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNum.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumDivider.cs
  BigNumWizardApp/BigNumWizardTests/Compare/CompareTest.cs
  BigNumWizardApp/BigNumWizardTests/DivideTest.cs
Labels: enhancement

#40 new pages navigate architecture
  BigNumWizardApp/BigNumWizardApp/ADD_NN_N_Page.xaml
  BigNumWizardApp/BigNumWizardApp/ADD_NN_N_Page.xaml.cs
  BigNumWizardApp/BigNumWizardApp/BigNumWizardApp.csproj
  BigNumWizardApp/BigNumWizardApp/MainPage.xaml
  BigNumWizardApp/BigNumWizardApp/MainPage.xaml.cs
  BigNumWizardApp/BigNumWizardApp/N2_NZER_N_B_Page.xaml
  BigNumWizardApp/BigNumWizardApp/N2_NZER_N_B_Page.xaml.cs
  BigNumWizardApp/BigNumWizardApp/N_2_NZER_N_B_Page.xaml.cs
  BigNumWizardApp/BigNumWizardApp/SUB_NN_N_Page.xaml
  BigNumWizardApp/BigNumWizardApp/SUB_NN_N_Page.xaml.cs
  BigNumWizardApp/BigNumWizardApp/SumNNPage.cs
  BigNumWizardApp/BigNumWizardApp/TwoNumbersPage.xaml
  BigNumWizardApp/BigNumWizardApp/TwoNumbersPage.xaml.cs
  BigNumWizardApp/BigNumWizardApp/Z2_POZ_Z_D_Page.xaml
  BigNumWizardApp/BigNumWizardApp/Z2_POZ_Z_D_Page.xaml.cs
  BigNumWizardApp/BigNumWizardApp/Z8_MUL_ZZ_Z_Page.xaml
Labels: enhancement

#42 Test Z1 (absolute value)
  BigNumWizardApp/BigNumWizardTests/Test_Z1.cs
Labels: enhancement

#44 Hotfix N11
  BigNumWizardApp/BigNumWizardShared/N11.cs
Labels: enhancement

#43 Test Z2
  BigNumWizardApp/BigNumWizardTests/Test_Z2.cs
Labels: enhancement

#47 Test N5
  BigNumWizardApp/BigNumWizardTests/Test_N5.cs
Labels: enhancement

#49 Bratsun
  BigNumWizardApp/BigNumWizardShared/N10.cs
Labels: enhancement

#48 Add Test_Z6
  BigNumWizardApp/BigNumWizardTests/Test_Z6.cs
Labels: bug, enhancement

#46 Bratsun
  BigNumWizardApp/BigNumWizardApp/N12.cs
Labels: enhancement

#50 Z3 test added
  BigNumWizardApp/BigNumWizardTests/Test_Z3.cs
Labels: enhancement

#51 Test N2
  BigNumWizardApp/BigNumWizardTests/Test_N2.cs
Labels: enhancement

#53 Test Z8
  BigNumWizardApp/BigNumWizardTests/Test_Z8.cs
Labels: enhancement

#52 added test Q7 and equality check for BigFractions
  BigNumWizardApp/BigNumWizardShared/BigFraction/BigFraction.cs
  BigNumWizardApp/BigNumWizardTests/Test_Q7.cs
Labels: enhancement

#54 Add z9
  BigNumWizardApp/BigNumWizardShared/Z9.cs
Labels: enhancement

#55 Tests for Q8 + edited Q8 (class wasn't public)
  BigNumWizardApp/BigNumWizardShared/Q8.cs
  BigNumWizardApp/BigNumWizardTests/Test_Q8.cs
Labels: enhancement

#57 added WAP project
  BigNumWizardApp/BigNumWizardApp.sln
  BigNumWizardApp/BigNumWizardWAP/BigNumWizardWAP.wapproj
  BigNumWizardApp/BigNumWizardWAP/Images/LockScreenLogo.scale-200.png
  BigNumWizardApp/BigNumWizardWAP/Images/SplashScreen.scale-200.png
  BigNumWizardApp/BigNumWizardWAP/Images/Square150x150Logo.scale-200.png
  BigNumWizardApp/BigNumWizardWAP/Images/Square44x44Logo.scale-200.png
  BigNumWizardApp/BigNumWizardWAP/Images/Square44x44Logo.targetsize-24_altform-unplated.png
  BigNumWizardApp/BigNumWizardWAP/Images/StoreLogo.png
  BigNumWizardApp/BigNumWizardWAP/Images/Wide310x150Logo.scale-200.png
  BigNumWizardApp/BigNumWizardWAP/Package.appxmanifest
Labels: enhancement
