Repository NikolaySavenko/bignum-wizard, pull requests merged in 2021-04, with the labels that each got.

#64 moved N12 from App to Shared
  BigNumWizardApp/BigNumWizardShared/N12.cs
Labels: bug, wontfix

#66 P3
  BigNumWizardApp/BigNumWizardShared/P12.cs
  BigNumWizardApp/BigNumWizardShared/P3.cs
  BigNumWizardApp/BigNumWizardShared/P4_5.cs
  BigNumWizardApp/BigNumWizardShared/Polynomial/Polynomial.cs
Labels: enhancement

#67 Bratsun
  BigNumWizardApp/BigNumWizardTests/Test_N7.cs
Labels: enhancement

#68 N13+test
  BigNumWizardApp/BigNumWizardShared/N4_13.cs
  BigNumWizardApp/BigNumWizardTests/Test_N13.cs
Labels: enhancement

#69 Test for N8, P6 + fixed P6
  BigNumWizardApp/BigNumWizardShared/P_6.cs
  BigNumWizardApp/BigNumWizardTests/Test_N8.cs
  BigNumWizardApp/BigNumWizardTests/Test_P6.cs
Labels: enhancement

#62 Test for Q2
  BigNumWizardApp/BigNumWizardTests/Test_Q2.cs
Labels: enhancement

#70 N12 test
  BigNumWizardApp/BigNumWizardTests/Test_N12.cs
Labels: enhancement

#71 Add Z7
  BigNumWizardApp/BigNumWizardShared/Z7.cs
Labels: enhancement

#74 LICENSE
  LICENSE.txt
  NOTICE.txt
Labels: documentation

#77 Hotfix/bignum const
  BigNumWizardApp/BigNumWizardShared/BigFraction/BigFraction.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumConst.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumDivider.cs
  BigNumWizardApp/BigNumWizardShared/N10.cs
  BigNumWizardApp/BigNumWizardShared/N2_6.cs
  BigNumWizardApp/BigNumWizardShared/N3_N7.cs
  BigNumWizardApp/BigNumWizardShared/P12.cs
  BigNumWizardApp/BigNumWizardShared/P4_5.cs
  BigNumWizardApp/BigNumWizardShared/Q2_3.cs
  BigNumWizardApp/BigNumWizardShared/Rational.cs
  BigNumWizardApp/BigNumWizardShared/Z7.cs
  BigNumWizardApp/BigNumWizardShared/z2_3.cs
  BigNumWizardApp/BigNumWizardTests/AbsTest.cs
  BigNumWizardApp/BigNumWizardTests/Negative/SumTest.cs
  BigNumWizardApp/BigNumWizardTests/Positive/SubtractionBigNumTest.cs
  BigNumWizardApp/BigNumWizardTests/Test_P6.cs
Labels: enhancement

#76 Added N14 and tests
  BigNumWizardApp/BigNumWizardShared/N8_14.cs
  BigNumWizardApp/BigNumWizardTests/Test_N14.cs
Labels: enhancement

#78 Hotfix/bignum definition split
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNum.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumCast.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumCompare.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumDivider.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumEnumerable.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumSubstraction.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumSummarize.cs
  BigNumWizardApp/BigNumWizardShared/Q2_3.cs
Labels: enhancement

#75 edited divider (it seems to work); Tests for N11 (divider); Q1
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumDivider.cs
  BigNumWizardApp/BigNumWizardShared/Q1.cs
  BigNumWizardApp/BigNumWizardTests/Test_N11.cs
Labels: enhancement

#79 Add test for z9
  BigNumWizardApp/BigNumWizardTests/Test_Z9.cs
Labels: enhancement

#80 Hotfix/common fixes
  BigNumWizardApp/BigNumWizardApp/MainPage.xaml.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNum.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumDebugger.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumDivider.cs
  BigNumWizardApp/BigNumWizardShared/N10.cs
  BigNumWizardApp/BigNumWizardTests/Test_N2.cs
  BigNumWizardApp/BigNumWizardTests/Test_N5.cs
  BigNumWizardApp/BigNumWizardTests/Test_Q2.cs
Labels: enhancement

#82 Q5 added
  BigNumWizardApp/BigNumWizardShared/Q5_7.cs
Labels: enhancement

#85 fix P3 P4 P5 P12
  BigNumWizardApp/BigNumWizardShared/P12.cs
  BigNumWizardApp/BigNumWizardShared/P3.cs
  BigNumWizardApp/BigNumWizardShared/P4_5.cs
  BigNumWizardApp/BigNumWizardShared/Polynomial/Polynomial.cs
Labels: enhancement

#81 Feature/test N9
  BigNumWizardApp/BigNumWizardTests/Test_N9.cs
Labels: enhancement

#84 test p3
  BigNumWizardApp/BigNumWizardTests/Test_P3.cs
Labels: enhancement

#83 More tests Z6.
  BigNumWizardApp/BigNumWizardShared/Z6.cs
  BigNumWizardApp/BigNumWizardTests/Test_Z6.cs
Labels: bug

#89 Bratsun
  BigNumWizardApp/BigNumWizardShared/P4_5.cs
  BigNumWizardApp/BigNumWizardTests/Test_P5.cs
Labels: enhancement

#88 edited test p3
  BigNumWizardApp/BigNumWizardTests/Test_P3.cs
Labels: enhancement

#87 test for P12
  BigNumWizardApp/BigNumWizardTests/Test_P12.cs
Labels: enhancement

#86 Feature/test compare
  BigNumWizardApp/BigNumWizardTests/Compare/CompareTest.cs
  BigNumWizardApp/BigNumWizardTests/Test_N9.cs
Labels: enhancement

#90 Hotfix/test p12 fix
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumConst.cs
  BigNumWizardApp/BigNumWizardTests/Test_P12.cs
Labels: enhancement

#92 Hotfix/insignificant zeros fix
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNum.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumCompare.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumDivider.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumMultiplier.cs
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumSubstraction.cs
Labels: enhancement

#94 Feature/test compare
  BigNumWizardApp/BigNumWizardTests/Compare/CompareTest.cs
Labels: enhancement

#93 Feature/test negative
  BigNumWizardApp/BigNumWizardTests/Compare/AbiggerB/CompareNegativeTests.cs
Labels: enhancement

#91 ADD P7!!!
  BigNumWizardApp/BigNumWizardShared/P7.cs
Labels: enhancement

#96 test for Q1 (doesn't work for very long numbers, check it after)
  BigNumWizardApp/BigNumWizardShared/Q1.cs
  BigNumWizardApp/BigNumWizardTests/Test_Q1.cs
Labels: enhancement

#99 N10 corrected
  BigNumWizardApp/BigNumWizardShared/N10.cs
Labels: enhancement

#98 edited test P5
  BigNumWizardApp/BigNumWizardTests/Test_P5.cs
Labels: enhancement

#97 edited test for P3 (PROBLEM FOUND)
  BigNumWizardApp/BigNumWizardTests/Test_P3.cs
Labels: enhancement

#101 Add Q-6
  BigNumWizardApp/BigNumWizardShared/Q6.cs
Labels: enhancement

#100 Q5 test
  BigNumWizardApp/BigNumWizardShared/Q5_7.cs
  BigNumWizardApp/BigNumWizardTests/test_Q5.cs
Labels: enhancement

#103 N10 correct
  BigNumWizardApp/BigNumWizardShared/N10.cs
Labels: enhancement

#104 add test Q6
  BigNumWizardApp/BigNumWizardTests/Test_Q6.cs
Labels: enhancement

#106 Added P1 P2 and tests P1 and P2, fixed polynomial equals
  BigNumWizardApp/BigNumWizardShared/P1_2.cs
  BigNumWizardApp/BigNumWizardShared/Polynomial/Polynomial.cs
  BigNumWizardApp/BigNumWizardTests/Test_P1.cs
  BigNumWizardApp/BigNumWizardTests/Test_P2.cs
  BigNumWizardApp/BigNumWizardTests/Test_P3.cs
Labels: bug, enhancement

#108 add Test N10 and correct N10
  BigNumWizardApp/BigNumWizardShared/N10.cs
  BigNumWizardApp/BigNumWizardTests/Test_N10.cs
Labels: enhancement

#109 add new test for p2
  BigNumWizardApp/BigNumWizardTests/Test_P2.cs
Labels: enhancement

#107 P7 correct
  BigNumWizardApp/BigNumWizardShared/P7.cs
Labels: enhancement

#95 Add Z10 and Test_Z10. Modified Natural1_5.SUB_NN_N
  BigNumWizardApp/BigNumWizardShared/Natural1_5.cs
  BigNumWizardApp/BigNumWizardShared/Z10.cs
  BigNumWizardApp/BigNumWizardTests/Test_Z10.cs
Labels: enhancement

#112 fixed polynomials equals
  BigNumWizardApp/BigNumWizardShared/Polynomial/Polynomial.cs
  BigNumWizardApp/BigNumWizardTests/Test_P1.cs
  BigNumWizardApp/BigNumWizardTests/Test_P2.cs
  BigNumWizardApp/BigNumWizardTests/Test_P3.cs
Labels: bug

#111 Added P9
  BigNumWizardApp/BigNumWizardShared/P9.cs
Labels: enhancement

#110 added test for P7
  BigNumWizardApp/BigNumWizardTests/Test_P7.cs
Labels: enhancement

#114 Test for Z7 and a few fixes
  BigNumWizardApp/BigNumWizardShared/P7.cs
  BigNumWizardApp/BigNumWizardShared/Z7.cs
  BigNumWizardApp/BigNumWizardTests/Test_Z7.cs
Labels: enhancement

#118 Test P4
  BigNumWizardApp/BigNumWizardTests/Test_P4.cs
Labels: enhancement

#121 expansions of N and Z module tests, fixes
  BigNumWizardApp/BigNumWizardShared/z2_3.cs
  BigNumWizardApp/BigNumWizardTests/Test_N2.cs
  BigNumWizardApp/BigNumWizardTests/Test_N3.cs
  BigNumWizardApp/BigNumWizardTests/Test_N6.cs
  BigNumWizardApp/BigNumWizardTests/Test_P12.cs
  BigNumWizardApp/BigNumWizardTests/Test_Z1.cs
  BigNumWizardApp/BigNumWizardTests/Test_Z3.cs
  BigNumWizardApp/BigNumWizardTests/Test_Z9.cs
Labels: enhancement

#120 Added Test P9 and edited P9
  BigNumWizardApp/BigNumWizardShared/P9.cs
  BigNumWizardApp/BigNumWizardTests/Test_P9.cs
Labels: enhancement

#119 n9
  BigNumWizardApp/BigNumWizardShared/N9.cs
  BigNumWizardApp/BigNumWizardTests/Test_N9.cs
Labels: enhancement

#123 Add incative P8
  BigNumWizardApp/BigNumWizardShared/P8.cs
Labels: bug, enhancement

#124 Edit modules and tests for polynom
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNum.cs
  BigNumWizardApp/BigNumWizardShared/P12.cs
  BigNumWizardApp/BigNumWizardShared/P1_2.cs
  BigNumWizardApp/BigNumWizardShared/P3.cs
  BigNumWizardApp/BigNumWizardShared/P4_5.cs
  BigNumWizardApp/BigNumWizardShared/P7.cs
  BigNumWizardApp/BigNumWizardShared/P9.cs
  BigNumWizardApp/BigNumWizardShared/P_6.cs
  BigNumWizardApp/BigNumWizardTests/Test_P1.cs
  BigNumWizardApp/BigNumWizardTests/Test_P12.cs
  BigNumWizardApp/BigNumWizardTests/Test_P2.cs
  BigNumWizardApp/BigNumWizardTests/Test_P3.cs
  BigNumWizardApp/BigNumWizardTests/Test_P4.cs
  BigNumWizardApp/BigNumWizardTests/Test_P5.cs
  BigNumWizardApp/BigNumWizardTests/Test_P6.cs
  BigNumWizardApp/BigNumWizardTests/Test_P7.cs
  BigNumWizardApp/BigNumWizardTests/Test_P9.cs
Labels: enhancement

#122 add Test P8
  BigNumWizardApp/BigNumWizardTests/Test_P8.cs
Labels: enhancement

#125 Hotfix/test fix
  BigNumWizardApp/BigNumWizardTests/DivideTest.cs
  BigNumWizardApp/BigNumWizardTests/Test_N5.cs
Labels: bug

#132 Added P11
  BigNumWizardApp/BigNumWizardShared/P11.cs
Labels: enhancement

#127 Big update
  BigNumWizardApp/BigNumWizardShared/Polynomial/Polynomial.cs
  BigNumWizardApp/BigNumWizardUWP/App.xaml
  BigNumWizardApp/BigNumWizardUWP/App.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardUWP.csproj
  BigNumWizardApp/BigNumWizardUWP/MainPage.xaml
  BigNumWizardApp/BigNumWizardUWP/MainPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/OneFractionPage.xaml
  BigNumWizardApp/BigNumWizardUWP/OneFractionPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/OneNumberPage.xaml
  BigNumWizardApp/BigNumWizardUWP/OneNumberPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/ThreeNumbersPage.xaml
  BigNumWizardApp/BigNumWizardUWP/ThreeNumbersPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/TwoFractionsPage.xaml
  BigNumWizardApp/BigNumWizardUWP/TwoFractionsPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/TwoNumbersPage.xaml
Labels: enhancement

#133 fix P8 and Test_P8
  BigNumWizardApp/BigNumWizardShared/P8.cs
  BigNumWizardApp/BigNumWizardTests/Test_P8.cs
Labels: enhancement

#134 P7 corrected last version
  BigNumWizardApp/BigNumWizardShared/P7.cs
Labels: enhancement

#135 Add P-10
  BigNumWizardApp/BigNumWizardShared/P10.cs
  BigNumWizardApp/BigNumWizardShared/P11.cs
Labels: enhancement

#136 Exceptions handling for modules P10, Q1, Q8 + a few test fixes
  BigNumWizardApp/BigNumWizardShared/N3_N7.cs
  BigNumWizardApp/BigNumWizardShared/P10.cs
  BigNumWizardApp/BigNumWizardShared/Q1.cs
  BigNumWizardApp/BigNumWizardShared/Q8.cs
  BigNumWizardApp/BigNumWizardTests/Test_P6.cs
  BigNumWizardApp/BigNumWizardTests/Test_P7.cs
  BigNumWizardApp/BigNumWizardTests/Test_Q1.cs
Labels: enhancement

#140 Working test P10
  BigNumWizardApp/BigNumWizardShared/P9.cs
  BigNumWizardApp/BigNumWizardTests/Test_P10.cs
Labels: enhancement

#141 Hotfix/bignum constructor fix
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNum.cs
  BigNumWizardApp/BigNumWizardTests/Test_Z6.cs
Labels: enhancement

#146 edited ConvertToInt
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNum.cs
Labels: enhancement

#145 Q and P tests expansion
  BigNumWizardApp/BigNumWizardShared/N4_13.cs
  BigNumWizardApp/BigNumWizardShared/P12.cs
  BigNumWizardApp/BigNumWizardTests/IntConvertationTest.cs
  BigNumWizardApp/BigNumWizardTests/Test_P1.cs
  BigNumWizardApp/BigNumWizardTests/Test_P12.cs
  BigNumWizardApp/BigNumWizardTests/Test_P5.cs
  BigNumWizardApp/BigNumWizardTests/Test_P7.cs
  BigNumWizardApp/BigNumWizardTests/Test_Q6.cs
  BigNumWizardApp/BigNumWizardTests/Test_Q7.cs
Labels: enhancement

#144 add test P2
  BigNumWizardApp/BigNumWizardTests/Test_P2.cs
Labels: enhancement

#142 fix Test Z-10, fix exception for Z-10 and N-5
  BigNumWizardApp/BigNumWizardShared/Natural1_5.cs
  BigNumWizardApp/BigNumWizardShared/Z10.cs
  BigNumWizardApp/BigNumWizardTests/Test_Z10.cs
Labels: fix

#138 Add not working tests for P11
  BigNumWizardApp/BigNumWizardTests/Test_P11.cs
Labels: bug

#147 deleted old wap
  BigNumWizardApp/WapProjTemplate1/Images/LockScreenLogo.scale-200.png
  BigNumWizardApp/WapProjTemplate1/Images/SplashScreen.scale-200.png
  BigNumWizardApp/WapProjTemplate1/Images/Square150x150Logo.scale-200.png
  BigNumWizardApp/WapProjTemplate1/Images/Square44x44Logo.scale-200.png
  BigNumWizardApp/WapProjTemplate1/Images/Square44x44Logo.targetsize-24_altform-unplated.png
  BigNumWizardApp/WapProjTemplate1/Images/StoreLogo.png
  BigNumWizardApp/WapProjTemplate1/Images/Wide310x150Logo.scale-200.png
  BigNumWizardApp/WapProjTemplate1/Package.appxmanifest
  BigNumWizardApp/WapProjTemplate1/WapProjTemplate1.wapproj
Labels: enhancement

#148 Edited p9
  BigNumWizardApp/BigNumWizardShared/P3.cs
  BigNumWizardApp/BigNumWizardShared/P9.cs
  BigNumWizardApp/BigNumWizardTests/Test_P9.cs
Labels: enhancement

#149 edited ConvertToInt
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNum.cs
  BigNumWizardApp/BigNumWizardShared/P10.cs
  BigNumWizardApp/BigNumWizardShared/P1_2.cs
  BigNumWizardApp/BigNumWizardTests/Test_P2.cs
Labels: enhancement

#150 Tests for P4
  BigNumWizardApp/BigNumWizardTests/Test_P4.cs
Labels: enhancement

#151 Add extra tests for P6
  BigNumWizardApp/BigNumWizardTests/Test_P6.cs
Labels: enhancement

#152 add P13
  BigNumWizardApp/BigNumWizardShared/P13.cs
Labels: enhancement

#153 fixed P11
  BigNumWizardApp/BigNumWizardShared/P11.cs
Labels: enhancement

#154 Edited P9
  BigNumWizardApp/BigNumWizardShared/P9.cs
  BigNumWizardApp/BigNumWizardTests/Test_P9.cs
Labels: enhancement

#156 Edited tests P10
  BigNumWizardApp/BigNumWizardTests/Test_P10.cs
Labels: enhancement

#157 fixed fixed P11
  BigNumWizardApp/BigNumWizardShared/P11.cs
Labels: enhancement

#159 fix BigNumDivider and add some tests for P8
  BigNumWizardApp/BigNumWizardShared/BigNum/BigNumDivider.cs
  BigNumWizardApp/BigNumWizardTests/DivideTest.cs
  BigNumWizardApp/BigNumWizardTests/Test_P8.cs
Labels: fix

#158 Add Test P11
  BigNumWizardApp/BigNumWizardTests/Test_P11.cs
Labels: enhancement

#161 Test p13
  BigNumWizardApp/BigNumWizardShared/P13.cs
  BigNumWizardApp/BigNumWizardTests/Test_P13.cs
Labels: enhancement

#162 Fixed test for N10
  BigNumWizardApp/BigNumWizardTests/Test_N10.cs
Labels: enhancement

#160 Feature/lottie startup
  BigNumWizardApp/BigNumWizardUWP/AnimatedVisuals/CalcLottie.cs
  BigNumWizardApp/BigNumWizardUWP/AnimatedVisuals/ClearCalc.cs
  BigNumWizardApp/BigNumWizardUWP/AnimatedVisuals/LottieLogo1_Modified.cs
  BigNumWizardApp/BigNumWizardUWP/App.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardPackage/Images/SplashScreen.scale-100.png
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardPackage/Images/SplashScreen.scale-125.png
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardPackage/Images/SplashScreen.scale-150.png
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardPackage/Images/SplashScreen.scale-200.png
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardPackage/Images/SplashScreen.scale-400.png
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardPackage/Package.appxmanifest
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardUWP.csproj
Labels: enhancement

#163 interface update
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardUWP.csproj
  BigNumWizardApp/BigNumWizardUWP/HelpPage.xaml
  BigNumWizardApp/BigNumWizardUWP/MainPage.xaml
  BigNumWizardApp/BigNumWizardUWP/MainPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/OneFractionPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/OneNumberPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/OnePolynomPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/ThreeNumbersPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/TwoFractionsPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/TwoPolynomPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/ValueChecker.cs
  BigNumWizardApp/BigNumWizardUWP/WelcomePage.xaml
Labels: bug, enhancement

#164 small improvements
  BigNumWizardApp/BigNumWizardApp.sln
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardPackage/BigNumWizardPackage.wapproj
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardPackage/Package.appxmanifest
  BigNumWizardApp/BigNumWizardUWP/BigNumWizardUWP.csproj
Labels: enhancement

#165 Edited P11 and P11 tests
  BigNumWizardApp/BigNumWizardShared/P11.cs
  BigNumWizardApp/BigNumWizardTests/Test_P11.cs
Labels: enhancement

#166 fix Z10 and beautiful tests for P8
  BigNumWizardApp/BigNumWizardShared/P8.cs
  BigNumWizardApp/BigNumWizardShared/Z10.cs
  BigNumWizardApp/BigNumWizardTests/Test_N5.cs
  BigNumWizardApp/BigNumWizardTests/Test_P8.cs
  BigNumWizardApp/BigNumWizardTests/Test_Z10.cs
Labels: fix

#167 Edited Q4 and Q6
  BigNumWizardApp/BigNumWizardShared/Q6.cs
  BigNumWizardApp/BigNumWizardShared/Rational.cs
Labels: enhancement

#168 Fixes
  BigNumWizardApp/BigNumWizardShared/P3.cs
  BigNumWizardApp/BigNumWizardShared/P4_5.cs
  BigNumWizardApp/BigNumWizardShared/Q8.cs
  BigNumWizardApp/BigNumWizardShared/Z10.cs
  BigNumWizardApp/BigNumWizardShared/Z9.cs
  BigNumWizardApp/BigNumWizardTests/Test_P1.cs
  BigNumWizardApp/BigNumWizardTests/Test_P3.cs
  BigNumWizardApp/BigNumWizardTests/Test_P4.cs
  BigNumWizardApp/BigNumWizardTests/Test_Q8.cs
Labels: enhancement

#169 update interface
  BigNumWizardApp/BigNumWizardUWP/HelpPage.xaml
  BigNumWizardApp/BigNumWizardUWP/MainPage.xaml
  BigNumWizardApp/BigNumWizardUWP/MainPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/OneFractionPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/TwoFractionsPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/TwoPolynomPage.xaml.cs
Labels: bug, enhancement

#170 P13 tests expansion
  BigNumWizardApp/BigNumWizardShared/Q5_7.cs
  BigNumWizardApp/BigNumWizardTests/IntConvertationTest.cs
  BigNumWizardApp/BigNumWizardTests/Test_P13.cs
Labels: enhancement, fix

#171 fix
  BigNumWizardApp/BigNumWizardUWP/OnePolynomPage.xaml.cs
  BigNumWizardApp/BigNumWizardUWP/TwoFractionsPage.xaml.cs
Labels: bug

#172 Q3 corrected
  BigNumWizardApp/BigNumWizardShared/Q2_3.cs
Labels: enhancement

#174 kolhoz in Z-10 fixed
  BigNumWizardApp/BigNumWizardShared/Z10.cs
Labels: fix

#175 Fixed Q7, Q8 + tests (added reduction)
  BigNumWizardApp/BigNumWizardShared/Q5_7.cs
  BigNumWizardApp/BigNumWizardShared/Q8.cs
  BigNumWizardApp/BigNumWizardTests/Test_Q7.cs
  BigNumWizardApp/BigNumWizardTests/Test_Q8.cs
Labels: fix
